title: Pelin Balcı's Blog
author:
  name: Pelin Balcı
  github: https://github.com/pelinbalci
description: > # this means to ignore newlines until "show_excerpts:"
  Machine Learning Notes
#description will appear in your document head meta (for Google search results)

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: balcipelin
    github:  pelinbalci
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: pelin-balci
    # pinterest: jekyll
    # youtube: @pelinbalci
    youtube_channel: UC7GKSxCvmkKTqMmb4w3-sxA
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: @pelinbalci
    #  instance: masto.ai
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - Apps.md
 - about.md
 - CV.md
 - BooksIRead(Okuduklarım).md

# Build settings
theme: jekyll-theme-minimal

plugins:
 - jekyll-feed
 - jekyll-seo-tag