# Site settings
title: Pelin Balci's Blog
email: -
description: > 
  Add description
baseurl: "/pelinbalci" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  pelinbalci

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock